server:
  port: 5001

spring:
  application:
    name: user

  datasource:
    url: "jdbc:mysql://localhost:3306/salon_userdb?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/